# Generated by Django 2.0.1 on 2018-06-12 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dawakhana', '0002_address_current'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='current',
        ),
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', related_query_name='address', to=settings.AUTH_USER_MODEL),
        ),
    ]
