# Generated by Django 2.0.1 on 2018-06-20 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dawakhana', '0007_auto_20180612_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_name', models.CharField(max_length=550, verbose_name='Medicine Name')),
                ('mc_name', models.CharField(max_length=950, verbose_name='Company Name')),
                ('m_type', models.CharField(choices=[('SYRUP', 'Syrup'), ('TABLETS', 'Tablets'), ('CAPSULES', 'Capsules')], max_length=550, verbose_name='Medicine Type')),
                ('m_quantity', models.CharField(max_length=250, verbose_name='Medicine Quantity')),
                ('description', models.CharField(max_length=950, verbose_name='Medicine Description')),
            ],
        ),
    ]
