# Generated by Django 2.0.1 on 2018-06-21 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dawakhana', '0009_auto_20180620_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=250, verbose_name='Salt Name')),
                ('medicine', models.ManyToManyField(related_query_name='salt', to='dawakhana.Medicine')),
            ],
        ),
    ]
