# Generated by Django 2.0.1 on 2018-06-21 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dawakhana', '0010_salt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='m_quantity',
        ),
        migrations.AddField(
            model_name='medicine',
            name='Discount',
            field=models.PositiveSmallIntegerField(default='0', verbose_name='Discount On Price'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='max_price',
            field=models.PositiveSmallIntegerField(default='0', verbose_name='MRP Of Medicine'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='mb_quantity',
            field=models.CharField(default='0', max_length=550, verbose_name='Single Box Quantity'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='ms_quantity',
            field=models.PositiveSmallIntegerField(default='0', verbose_name='Stock Quantity'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='our_price',
            field=models.PositiveSmallIntegerField(default='0', verbose_name='Pharmacist Price Of Medicine'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='description',
            field=models.TextField(max_length=950, verbose_name='Medicine Description'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='m_type',
            field=models.CharField(choices=[('SYRUP', 'Syrup Bottle'), ('TABLETS', 'Tablets'), ('CAPSULES', 'Capsules')], max_length=550, verbose_name='Medicine Type'),
        ),
        migrations.AlterField(
            model_name='salt',
            name='medicine',
            field=models.ManyToManyField(related_query_name='salt', to='dawakhana.Medicine'),
        ),
    ]
