# Generated by Django 2.0.1 on 2018-06-26 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dawakhana', '0012_auto_20180625_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='organization',
        ),
        migrations.AddField(
            model_name='user',
            name='dlno',
            field=models.CharField(default='null', max_length=250, verbose_name='Drug License no.'),
        ),
        migrations.AlterField(
            model_name='salt',
            name='medicine',
            field=models.ManyToManyField(related_query_name='salt', to='dawakhana.Medicine'),
        ),
        migrations.AlterField(
            model_name='salt',
            name='s_quantity',
            field=models.CharField(default=' ', max_length=250, verbose_name='Salt Quantity'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'female')], default=' ', max_length=7, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='user',
            name='title',
            field=models.CharField(choices=[('MR.', 'Mr.'), ('MRS.', 'Mrs.')], default=' ', max_length=4, verbose_name='Title'),
        ),
    ]
