# Generated by Django 2.0.1 on 2018-06-27 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dawakhana', '0014_auto_20180627_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.CharField(default='', max_length=350, verbose_name='Comapny Name'),
        ),
        migrations.AlterField(
            model_name='salt',
            name='medicine',
            field=models.ManyToManyField(related_query_name='salt', to='dawakhana.Medicine'),
        ),
    ]
